baseurl      = "https://qxzzf.com"
title        = "天心流水的博客"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]

[author]
  name = "天心流水"

[blackfriday]
  hrefTargetBlank = true

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  homeSubtitle = "日々私たちが過ごしている日常は、実は、奇跡の連続なのかもしれない"

  disableReadOtherPosts = false
  enableSharingButtons = true

  description = "天心流水的个人博客"
  keywords = "homepage, blog"
  images = [""]

  defaultTheme = "dark"

[taxonomies]
  category = "blog"
  tag      = "tags"
  series   = "series"

[languages]

  [languages.en]
    title = "天心流水的博客"
    subtitle = "每天进步一点点"
    keywords = "技术,日常,碎碎念"
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "阅读更多"

    [languages.en.params.logo]
      logoText = "首页"
      logoHomeLink = "/"

[menu]
  [[menu.main]]
    identifier = "blog"
    name       = "文章"
    url        = "/posts/"
  [[menu.main]]
    identifier = "search"
    name       = "搜索"
    url        = "/search"

  [[params.social]]
    name = "email"
    url  = "mailto:857995137@qq.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/takashiki"
